### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Lepidopteron** [IvanMathy/Boop#10]
Text uppercased / lowercased would be awesome!

Thank you for your App.

**Comment by IvanMathy** [comment]
Looks like #17 wants to solve this issue. The original idea was that Uppercase and Lowercase are available under the `Edit > Transformations` menu, so it seemed a bit redundant. I'd be happy to still add it in!

**Comment by IvanMathy** [comment]
Fixed in #17
