### ISSUE TITLE
Typo in JSONtoCSV.js

### ISSUE THREAD

**Issue by mrbenshef** [IvanMathy/Boop#110]
`JSONtoCSV.js` is the only script that calls `state.error(..)`, but it doesn't appear in the documentation or the code from what I could tell, should this be `state.postError(..)`?

https://github.com/IvanMathy/Boop/blob/ddcb529a805df1fba6b3c8d1369fd0a6ee63073f/Boop/Boop/scripts/JSONtoCSV.js#L26

**Comment by IvanMathy** [comment]
That's a good catch, thanks! Would you mind opening a PR that fixes it? Otherwise I can take care of it in a little bit.
