### ISSUE TITLE
Feature request for hash functions to hash text

### ISSUE THREAD

**Issue by klundberg** [IvanMathy/Boop#116]
I'd love to be able to paste some text into boop and then have an option to get the output of feeding that text in popular hash functions, like sha256! Probably for simplicity it could/should use the string's utf8 representation, but if there's some way to be able to choose encoding that could work too.

Thanks for the awesome app!

**Comment by IvanMathy** [comment]
Hey there! Thanks for the suggestion!

I'd love to add more hashing/crypto functions. Feel free to list everything you'd like, it makes easier to know how to implement it.

**Comment by klundberg** [comment]
Sure. The main ones I'd think of using would be SHA-256, and SHA-3. I know there's other SHA variants but this would be a good starting point.

SHA-1 would be useful too, but I won't argue strongly for that since it's insecure :). I can see that MD5 is already supported though, so maybe despite SHA-1 being broken, that can be included for completeness.

Additionally, it'd be awesome to be able to type something like "hash" to see all the supported hash functions in the search box instead of having to guess which ones are implemented by their official names :)

**Comment by klundberg** [comment]
I just realized that #56 takes care of this too (at least in part)! I should've looked at the PRs before opening this issue :)

**Comment by nhnicwaller** [comment]
I'm confused. I already see [SHA256.js](https://github.com/IvanMathy/Boop/blob/main/Boop/Boop/scripts/SHA256.js) in the built-in scripts, but it doesn't appear for me in the scripts picker. Is the script broken/failing to load somehow?

**Comment by IvanMathy** [comment]
Hey @nhnicwaller,

Those scripts have not yet been released, son you won't see them unless you build from source. I'm planning to get 1.3.0 out the door soon, so you'll be able to get them there.

Closing the issue in the meantime, feel free to reopen or add a new one if you have any problem with it!
