### ISSUE TITLE
Bug: URL encoding an Emoji leaves an unreadable character at the end

### ISSUE THREAD

**Issue by oliveratgithub** [IvanMathy/Boop#123]
When URL encoding an Emoji, it does correctly convert it - but leaves an unreadable character at the very end.

### Example:
* Input: `👍`
* Action: `URL Encode`
* Expected result: `%F0%9F%91%8D`
* Actual result:<br><img width="246" alt="image" src="https://user-images.githubusercontent.com/280207/87810955-21eeca80-c85e-11ea-9d70-71dce8b01f19.png">

### Version details
* Boop Version 1.1.0 (3)
* macOS Big Sur 11.0 Beta (20A4300b)

**Comment by IvanMathy** [comment]
Hey there! This bug is fixed in Boop 1.2.0, which should hopefully come out tomorrow 👍

**Comment by IvanMathy** [comment]
1.2.0 is now out! Closing this issue.
