### ISSUE TITLE
Feature request: ability to mouse click a command in the result list

### ISSUE THREAD

**Issue by oliveratgithub** [IvanMathy/Boop#124]
It would be a welcomed small addition, to not only be able to select a result entry using the mouse cursor + click, but also double-click (as example) to actually execute it.

Example:
<img width="480" alt="image" src="https://user-images.githubusercontent.com/280207/87811577-2b2c6700-c85f-11ea-8378-85721ed28663.png">

Can only be triggered with the `Return`-key - but not with a mouse click or double-click.

**Comment by IvanMathy** [comment]
Hey there! Thanks for the reminded, I know about this issue but I keep forgetting to fix it... I'll get it in 1.3.0.
