### ISSUE TITLE
join lines with comma only one row is in effect

### ISSUE THREAD

**Issue by lybc** [IvanMathy/Boop#129]
Install from App Store

Version 1.2.0 (5)

## script code
```javascript
/**
	{
		"api":1,
		"name":"Join Lines With Comma",
		"description":"Joins all lines with a comma.",
		"author":"riesentoaster",
		"icon":"collapse",
		"tags":"join, comma",
		"bias": -0.1
	}
**/

function main(state) {
    state.text = state.text.replace('\n', ',');
}
```

## input
![image](https://user-images.githubusercontent.com/9601872/88033927-8d90aa80-cb72-11ea-8e52-b4235186580f.png)

## output
![image](https://user-images.githubusercontent.com/9601872/88033873-7baf0780-cb72-11ea-8ce5-6baf10d91815.png)

**Comment by IvanMathy** [comment]
Hey there! Thanks for the report, I'll take a look... In the meantime you can use the built in `collapse` script that works as expected.

Closing this issue since it's  tracked by #128 as well
