### ISSUE TITLE
Feature Request: Let me install with homebrew!

### ISSUE THREAD

**Issue by Tyler-Keith-Thompson** [IvanMathy/Boop#13]
Excited to use the product. Would you be willing to turn this into a homebrew cask?

**Comment by IvanMathy** [comment]
I can definitely look into it. Managing both GitHub and Mac App Store release is already quite the task, so I'll see how much effort it would require.

Thanks for the request!

**Comment by jayqi** [comment]
Here's some documentation about criteria for Homebrew casks from their Rejection FAQ:

> The Cask is for an app that is too obscure. Examples:
> - A self-submitted app from a GitHub repository that is not notable enough (under 30 forks, 30 watchers, and 75 stars).

https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md

This repo has more stars than that, so maybe it's notable enough!

**Comment by IvanMathy** [comment]
Thanks Jay! It seems like it was added by @jfsimoneau:

https://github.com/Homebrew/homebrew-cask/commit/9ed131a3971c3a90d8928415d86c7ed37856886a

Closing the issue for now, let me know if there is anything else needed from me
