### ISSUE TITLE
buggy inputting

### ISSUE THREAD

**Issue by RedStarOverChina** [IvanMathy/Boop#136]
Boop will be buggy when users input languages like Japanese or Chinese
inputting:
<img width="570" alt="image" src="https://user-images.githubusercontent.com/59812831/88372302-32f08c00-cdc8-11ea-8d09-d359412f1223.png">
inputted:
<img width="592" alt="image" src="https://user-images.githubusercontent.com/59812831/88372412-6f23ec80-cdc8-11ea-908b-c7830acddecb.png">

**Comment by IvanMathy** [comment]
Hey there! Thanks for the report. I just fixed it in and will make a new release ASAP so you can try it.

**Comment by RedStarOverChina** [comment]
> Hey there! Thanks for the report. I just fixed it in and will make a new release ASAP so you can try it.

really thx

**Comment by IvanMathy** [comment]
1.2.1 is now out with the fix, so I'm closing the issue but feel free to re-open it if it still doesn't work.

Thanks for the help!
