### ISSUE TITLE
Encode your email address with character entities

### ISSUE THREAD

**Issue by kimonostereo** [IvanMathy/Boop#138]
Not an issue but a feature request: ability to encode email with character entities similar to this website. http://www.wbwip.com/wbw/emailencoder.html

**Comment by IvanMathy** [comment]
Hey there!

That's a great idea, thanks! It would totally be possible. If you want, you can try your hand at making the script yourself and open a PR, or I'll try to work on it sometime soon.

**Comment by IvanMathy** [comment]
I goofed up the PR, but it's now fixed in the main branch. I'll release the new script, called "HTML Encode All Characters" in the next update!
