### ISSUE TITLE
Feature Request: Text Services Integration

### ISSUE THREAD

**Issue by m4p** [IvanMathy/Boop#14]
It would be quite powerful if Boop could be launched by selection text in any application, ctrl-clicking and using the Services menu.

E.g.:

![Screenshot 2020-06-16 at 17 28 39](https://user-images.githubusercontent.com/666042/84794709-de9f0300-aff6-11ea-96d3-2edf12450579.png)

**Comment by IvanMathy** [comment]
That's a very good feature request thanks! Did not even think of it.

I'll look into it, might not be a next release kind of thing but I'd love to add it sooner than later.

**Comment by m4p** [comment]
Best thing about this: You get a global hotkey for free. (Can be configured in System Prefs, Keyboard, Shortcuts). I can now select text, press command-option-ctrl-shift-b and it opens in Boop.

**Comment by IvanMathy** [comment]
Wow that was quick! Thank you so much for the PR, I'll review ASAP.

Would you know by any chance if I need additional entitlements for the App Store?

**Comment by m4p** [comment]
Afaik no additional entitlements needed.

**Comment by IvanMathy** [comment]
Fulfilled by #36
