### ISSUE TITLE
Crash when selecting action

### ISSUE THREAD

**Issue by Brett-Best** [IvanMathy/Boop#15]
1. Open Boop
2. Press Command+B
3. Type J
4. Hit Down Arrow
5. Hit Enter

Boop crashes with the below:
>*** Assertion failure in CGEventRef NSEventToCGEventRef(NSEvent *)(), /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1894.60.100/AppKit.subproj/NSEvent.m:2059
>
>Printing description of exception->exception:
Unrecognized event type 0
(null)

[Boop_2020-06-17-003441_Bretts-iMac.crash.txt](https://github.com/IvanMathy/Boop/files/4787514/Boop_2020-06-17-003441_Bretts-iMac.crash.txt)

I couldn’t find much information around in terms of what could be causing this issue.
I can raise a Feedback with Apple if it looks like an issue with macOS, also just a note that I am running 10.15.6 Beta (19G46c).

UPDATE:
This is caused by https://github.com/IvanMathy/Boop/blob/ba24395239b3051903345e46f27e53c8a502b8d6/Boop/Boop/Controllers/PopoverViewController.swift#L101, returning the original event stops the crash.

**Comment by IvanMathy** [comment]
Very strange, not seeing this on 10.15.5... I'll look into it and get back to you.

**Comment by Brett-Best** [comment]
You should be able to catch it in the debugger with an Exception Breakpoint
