### ISSUE TITLE
Input limit lines - buffer - crash

### ISSUE THREAD

**Issue by uhlhosting** [IvanMathy/Boop#157]
Hi

It seems when one tries to import some more lines like in my case I work with 30000 - 50000 lines simple txt, usual in domain form.

This is going to crash Boop without allowing it to do anything, frozen. No errors are reported.

Would be great to increase the ability to add more lines and paste them, or add direct by unloading files directly and reading their content.

I attach here a file that crashes when I import the content.

<img width="380" alt="image" src="https://user-images.githubusercontent.com/6324047/91102942-875a8600-e66a-11ea-97a2-56ab3c0e97ac.png">

[disavow domain.txt](https://github.com/IvanMathy/Boop/files/5120512/disavow.domain.txt)

[Spindump.txt](https://github.com/IvanMathy/Boop/files/5120524/Spindump.txt)
[Sample of Boop.txt](https://github.com/IvanMathy/Boop/files/5120525/Sample.of.Boop.txt)

Hope this helps to track and solve this. A limit of 100000 would be great yet Il handle also 50000 or 30000 even not sure what is current buffer limit in boop.

**Comment by IvanMathy** [comment]
Oooh, that's strange for sure... I'll look into it thank you!

**Comment by IvanMathy** [comment]
Fixed! It'll be released soon as part of update 1.3.0 👍
