### ISSUE TITLE
Pasting links from Safari

### ISSUE THREAD

**Issue by lastfuture** [IvanMathy/Boop#160]
When I right-click -> copy Link in Safari, and paste it into my usual plaintext editors I get the URL. In Boop I get the title of the link instead. Is this intentional? I'd prefer the regular plaintext behavior.

**Comment by IvanMathy** [comment]
Hello! Good catch, I think it'd be great to fix it. I'll try to get it in the next release. Thanks for the report!

**Comment by IvanMathy** [comment]
Fixed! It'll be released soon as part of update 1.3.0 👍

**Comment by lastfuture** [comment]
Awesome, thank you <3
