### ISSUE TITLE
Cannot mutate fullText after reading selection

### ISSUE THREAD

**Issue by nhnicwaller** [IvanMathy/Boop#174]
I'm trying to write a script that uses `selection` as an input parameter, then replaces `fullText` at the end. However, I've found that attempting to overwrite `fullText` fails if I've already read `selection` earlier in the script.

### Minimal Test Case

```
function main(state) {
	let input = state.selection;
	state.fullText = "";
}
```

### Expected Result

- The document is empty after running the script, regardless of selection

### Actual Result

- ❌ If some text is selected (`typeof state.selection === 'string'`) then the document doesn't change at all.
- ✅ If no text is selected (`typeof state.selection === 'undefined'`) then the document is cleared.

**Comment by IvanMathy** [comment]
This is a byproduct of the ability to have multiple selections. To avoid running the same result on `fullText`several times in a row and have unexpected results, the full text variable is ignore while in selection mode.

If this is something you have a good use case for, I'd be happy to consider changing it!

**Comment by nhnicwaller** [comment]
> If this is something you have a good use case for, I'd be happy to consider changing it!

I wanted to write a script that would  `eval()` some arbitrary JavaScript that I type right inside Boop, and map that transformation onto every line in the document. My goal was to use the selection as input, because there aren't really any other options for input.

It's not a very important use case though. 🤷‍♂️
