### ISSUE TITLE
⌘+W doesn’t work

### ISSUE THREAD

**Issue by mladenny** [IvanMathy/Boop#18]
Pressing ⌘+W doesn’t work in both the main window and the Boop Preferences.

macOS 10.14.6 (18G5033)

**Comment by sohan-shingade** [comment]
I want to try to solve this, but what exactly is ⌘+W supposed to do?

**Comment by sohan-shingade** [comment]
If ⌘+W is supposed to close the application, why not just use ⌘+Q?
