### ISSUE TITLE
Support for JavaScript Object <--> JSON

### ISSUE THREAD

**Issue by FrankKair** [IvanMathy/Boop#188]
Thought it would be nice to have support for JavaScript Objects and JSON conversions since it's a pretty common task when working with APIs and the Web in general.

Of course it's easy to just JSON.stringify, but I like to use Boop for these things.

**Comment by IvanMathy** [comment]
Hey there, sorry for the delqy in getting bqck to you! @luisfontes19's script is now available in main and will be part of the next release. Closing the issue, feel free to reopen if needed!
