### ISSUE TITLE
Base64 is wrong

### ISSUE THREAD

**Issue by Lapsusone** [IvanMathy/Boop#292]
Trying to encode "test123" using Boop version 1.3.1 and CLI.
Boop gives: dGVzdDEyMw==
CLI gives: dGVzdDEyMwo=

**Comment by chrislambe** [comment]
Assuming you're doing the following:

```
echo "test123" | base64
```

The difference between the two is that `echo` adds a newline character to the string. The CLI and Boop output match if you remove the newline character like so:

```
echo -n "test123" | base64
```
