### ISSUE TITLE
Output JavaScript errors to Console log

### ISSUE THREAD

**Issue by fnky** [IvanMathy/Boop#30]
It is currently difficult to debug scripts because errors are truncated in the "display" area and there is no way to see the full message:

![Error is truncated in Boop](https://user-images.githubusercontent.com/995050/84815900-9d651e00-b00b-11ea-8f4e-1e4c992fcb4d.png)

To make debugging a bit easier, it would be nice if Boop would output errors thrown by the JavaScriptCore sandbox so that they can be traced in the Console app.

**Comment by IvanMathy** [comment]
Yep, adding a proper console is next up. Also good idea, I'll see if I can route it all to Console.app in the meantime.

**Comment by IvanMathy** [comment]
Fixed in #115, look for it in the next release (though you'll need a dev build)!
