### ISSUE TITLE
Format single quoted JSON

### ISSUE THREAD

**Issue by sachindayl** [IvanMathy/Boop#309]
Formatting a single-quoted JSON body gives invalid JSON. Please check if the body has single quotes, convert them to double quotes, and then format JSON.

**Comment by Joshfindit** [comment]
I will likely make a script for "Convert all quotes to single quotes" and "Convert all quotes to double quotes" which would mean that this issue could be closed as a user would be able to convert quotes before formatting.

**Comment by sachindayl** [comment]
That should work!  thank you.

**Comment by Joshfindit** [comment]
Added those scripts:

https://github.com/IvanMathy/Boop/pull/336/files

Feel free to download them and add them to your scripts folder.
