### ISSUE TITLE
Support Math functions

### ISSUE THREAD

**Issue by fnky** [IvanMathy/Boop#32]
The idea is to introduce the whole—or a subset—of [Math](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math) object as [specified by ECMAScript](https://tc39.es/ecma262/#sec-math-object).

This would make it easier to access common Math functions such as `random`, `sin`, `cos`, `floor` and `ceil` and more.

One use case would be to randomly shuffle a list using [`Math.random`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random):

```js
function shuffleArray(array) {
  let tmp = [...array];

  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
	tmp[i] = tmp[j];
    tmp[j] = tmp[i];
  }

  return tmp;
}
```

**Comment by spoike** [comment]
I just tested and Math already works in Boop.

**Comment by fnky** [comment]
You're right. I got confused with another reference error.

Closing the thread.
