### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by IvanMathy** [IvanMathy/Boop#38]
Currently, the syntax highlighting is not super optimized, which cause performance issues on large strings.

Possible solutions:

- Migrate away from regex (Would this help?)
- Disable any multi-line regex, to see if it speeds things up.
- Add lazy highlighting. Only highlight viewport, and only when changed.

**Comment by fnky** [comment]
I think most of the performance can be won by the third solution. This is a common solution in most IDEs which also use regex-based syntax highlighting.

Not sure what you mean by the following:

> Only highlight viewport, **and only when changed**

Is it when viewport has changed (e.g. resizing, scrolling) or upon changing the content?

**Comment by IvanMathy** [comment]
> Is it when viewport has changed (e.g. resizing, scrolling) or upon changing the content?

Both, though I'd say the first step would be only when changing the content, on a line-per-line basis. Since it's using NSAttributedString in the background, resizing  and scrill won't change anything if the whole thing already got rendered.

**Comment by fnky** [comment]
Wouldn’t this mean that pasting large amount of text would be slow if it had to parse all the text to highlight it.

I can see an issue if it only highlights the text that is visible in the viewport. Scrolling and resize would not update the highlighting.

**Comment by IvanMathy** [comment]
Correct, first paste would be a bit slow but I think that's an ok tradeoff for a first improvement. The biggest issue right now is the slowness when typing in a large document

**Comment by IvanMathy** [comment]
Fixed in release 1.3.0
