### ISSUE TITLE
Website paragraph overflow bug

### ISSUE THREAD

**Issue by sobolevn** [IvanMathy/Boop#44]
This how one paragraph looks like on firefox and macos:
<img width="695" alt="Снимок экрана 2020-06-17 в 11 37 45" src="https://user-images.githubusercontent.com/4660275/84875763-135e9900-b08f-11ea-8fe6-89703d456ae6.png">

There's clearly not enough space for the text.
Link: https://boop.okat.best/

**Comment by fnky** [comment]
I'm sure this is intentional and meant as a joke for endless shaming.

**Comment by sobolevn** [comment]
> tpyescrpit • ndoe.js • reatc • dseginer • orthographist

😆 

I am not very good at jokes!

**Comment by IvanMathy** [comment]
Hi @sobolevn, it looks like this might be a problem with your computer. I suggest trying to download more ram or maybe switching to [Google Ultron](https://www.youtube.com/watch?v=dQw4w9WgXcQ).

Let me know if that solves the issue!

**Comment by sobolevn** [comment]
😆 

Thanks!
