### ISSUE TITLE
Improve Newline Handling

### ISSUE THREAD

**Issue by jnozzi** [IvanMathy/Boop#46]
Several existing scripts assume `\n` as the line break. I see two possible solutions:

**1:** We could include and use something like [node-newline](https://github.com/danielchatfield/node-newline) to avoid making assumptions about newlines.

**2:** Alternatively, we could enforce line normalization to `\n` when requesting the state's fullText / text / selection.

**Comment by IvanMathy** [comment]
Hey there! Thanks for the suggestion. Do you have any special cases I could try out to see if it's an issue? Thanks!

**Comment by jnozzi** [comment]
For plaintext input such as CSV (for which there exists a convert-to-JSON script), I can imagine pasting in contents pulled from text files from various platforms. I think just creating a test document with BBEdit and setting the line endings to something other than `\n` would suffice. I admit I haven't tested Boop's behavior here; this only occurred to me when looking at the existing scripts as examples. It may be that a trip through the pasteboard or pasting into the text view may normalize line endings but that would surprise me a bit.

I've attached a zip with 3 text files, named for their line endings. I used the `file` command to make sure BBEdit was telling the truth. I then opened each with TextEdit and copy/pasted into Boop to make sure BBEdit wasn't trying to be too clever.

`LineEndingTest-CRLF.txt` 

```
[
  {
    "ColA": "A",
    "ColB": "B",
    "ColC\r": "C\r"
  },
  {
    "ColA": "1",
    "ColB": "2",
    "ColC\r": "3\r"
  },
  {
    "ColA": ""
  }
]3


```

`LineEndingTest-CR.txt`

```
[
  {
    "2": "2",
    "3": "3\r",
    "ColA": "ColA",
    "ColB": "ColB",
    "ColC\rA": "ColC\rA",
    "B": "B",
    "C\r1": "C\r1"
  }
]
```

`LineEndingTest-LF.txt`

```
[
  {
    "ColA": "A",
    "ColB": "B",
    "ColC": "C"
  },
  {
    "ColA": "1",
    "ColB": "2",
    "ColC": "3"
  },
  {
    "ColA": ""
  }
]
```

[LineEndingTestFiles.zip](https://github.com/IvanMathy/Boop/files/4798206/LineEndingTestFiles.zip)

**Comment by KenCoder** [comment]
Also, for me, using JSON to CSV then copying to clipboard adds \r\n (I see it in clipboard viewer), which when pasting into certain apps (google sheets for example) causes an extra line feed. 

My recommendation is have boop be permissive on input (accept \r\n) but then use \n on all outputs everywhere (2 in the original post)
