### ISSUE TITLE
Display Full List of Available Scripts

### ISSUE THREAD

**Issue by robmathers** [IvanMathy/Boop#48]
Having a way to see all the available scripts would make it a little more discoverable as a new user. I ended up typing random letters in the picker to see what's available.

**Comment by esaruoho** [comment]
yeah i also want to see a full list instead of typing in random letters.

**Comment by IvanMathy** [comment]
Hey there! You can see the list of scripts by searching for `*`in the picker.

**Comment by cgarrovillo** [comment]
> Hey there! You can see the list of scripts by searching for `*` in the picker. I'll make it more clear in the documentation.

Instead of needing to type `*`, could it just be shown by default when the picker is opened?

From a UI/UX perspective, a user will always open the picker anyway, regardless of whether they know the scripts.

**Comment by cgarrovillo** [comment]
#148

**Comment by rmeister345** [comment]
I agree, seeing the list by default would be a much better experience in my case.  
So far I really like the app tho, good job.

**Comment by MarqueIV** [comment]
Agree with the others.  While having the option to use * to show everything is a work-around, it's not really great UI design and some could argue it breaks standards.  When you bring up the list originally, you should see everything, then as you type, it filters down.  That way you can explore implicitly.  I even branched your code to try adding that feature alone. If I get it working, I'll post a PR to you for inclusion. (That said, I have no idea when, or even if, I will get around to doing so so if you could add it from your end, that would be great.)
