### ISSUE TITLE
character count, 1) update on new characters 2) preference to stop hiding count result

### ISSUE THREAD

**Issue by esaruoho** [IvanMathy/Boop#53]
Hi, I currently use Boop for counting characters.
It would appear, that the result gets wiped after a few seconds. Why? What if I don't want the result to be wiped after a few seconds? What if I want to type some more, and see the character count update in real time?

**Comment by IvanMathy** [comment]
Hey there! The results of a script go away after 5 seconds by default, but I'm planning to extend that to stay on longer in the next version. As for updating in real time, that's not currently supported as scripts are meant to be run synchronously, so they are run only once when you select them as opposed to staying on while you type.

Unfortunately that's a byproduct of the architecture, so it most likely won't change anytime soon. However, you could get an easy re-run of the lqst script by pressing `⌘⇧B`, which will update the count without having to select the script again.
