### ISSUE TITLE
Feature Request: Encoding/Decoding JWTs

### ISSUE THREAD

**Issue by cesarbiods** [IvanMathy/Boop#78]
Functionality like that found in https://jwt.io would be awesome. I would love to work with JWTs in a native app instead of another web app. I'm not a swift developer but I would even be willing to help/contribute to make it happen.

**Comment by IvanMathy** [comment]
Hey there! Decoding is now available within version 1.1.0! I'm not sure how encoding would work, what do you have in mind?

**Comment by cesarbiods** [comment]
Thank you! Sorry I meant decoding and not encoding since my flow involves services generating JWTs and I just need to decode and validate their contents. Kudos for making it happen so quickly and distributing this app for free on the app store! 👍
