### ISSUE TITLE
dynamic reload of custom scripts

### ISSUE THREAD

**Issue by brokosz** [IvanMathy/Boop#81]
Really liking Boop! Is it possible to monitor the custom scripts folder so I don't have to quit and reopen the app the reload new scripts or changes?

**Comment by IvanMathy** [comment]
Hey there! 

No need to restart the app, you can easily reload custom scripts by either going in the `Scripts > Reload Scripts` menu or by pressing ⇧⌘R.

Auto reload could be cool, I'll look into it. Thanks!

**Comment by brokosz** [comment]
Missed the menu option. Thanks!!!
