### ISSUE TITLE
Default Feature Request [Format SQL]

### ISSUE THREAD

**Issue by fourcolors** [IvanMathy/Boop#83]
I would love to be able to format SQL dumps out of the box. I have to read queries from the terminal all the time and go to a site to format them. 

Looking into making my own script.

**Comment by IvanMathy** [comment]
Ooooh that's a cool idea, thanks! If you can get it going in a custom script, feel free to open a PR, otherwise I'll try to get to it at some point.

**Comment by IvanMathy** [comment]
Solved in #102, alongside SQL minify. Look for it in the next release!
