### ISSUE TITLE
Add support for JSON -> YAML and YAML -> JSON

### ISSUE THREAD

**Issue by nesl247** [IvanMathy/Boop#86]
Please add support for JSON to YAML and YAML to JSON.

Thanks!

**Comment by IvanMathy** [comment]
Great idea, I'll look into it. Thanks for the suggestion!

**Comment by fernakano** [comment]
I figure doing the JSON to YAML is quite simple, but the other way arrant YAML->JSON maybe not be as simple as existing available OSS libraries ar often much more complex.

I can do a partial JSON to YAML and do a pull request, would that be acceptable and leave just the YAML->JSON open?

**Comment by nesl247** [comment]
If the scripts are all in JS, then it should be relatively easy enough to use https://github.com/nodeca/js-yaml for the yaml handling, and just use native JSON support. Not sure exactly how boop is written for these scripts, but we do this kind of thing in our infrastructure code, and works without any configuration.

**Comment by IvanMathy** [comment]
Fixed! It'll be released soon as part of update 1.3.0 👍
