### ISSUE TITLE
Support UTF-8 character set

### ISSUE THREAD

**Issue by jschuster** [IvanMathy/Boop#90]
This Base64 encoded text:
4p2k77iP

should result in (Base64 decoded):
❤️

And vice versa.

Actual it results in
â¤ï¸

(I guess the ascii representation).

**Comment by IvanMathy** [comment]
Heh, that's actually something I have run into while using Boop for work. I created a custom script to deal with that. I'm not opposed to switching to utf8 as the default encoding for base 64, I'd have to look into the implications though.

Thanks for the suggestion!

**Comment by jschuster** [comment]
Hey Ivan, that would be awesome!
Love Boop - very clever tool for recurring tasks. Would love to ditch my old habits to e.g. open browser -> google -> base64encoder... ;)

Encoding stuff is always a pain.

A good test of implementations handling text is to use unicode characters > U+FFFF - my first test is always using the 💩 (U+1F4A9). If that works (e.g. sending -> receiving, converting back and forth), everything else should work as well.

I'm not into JS but it seems it's not quite trivial to support unicode. Stumbled upon this post among others:
https://dmitripavlutin.com/what-every-javascript-developer-should-know-about-unicode/

**Comment by IvanMathy** [comment]
Fixed in #94, look for it in the next version!
