### ISSUE TITLE
Bug When Running Script on Full Text with Unicode

### ISSUE THREAD

**Issue by cdfmlr** [IvanMathy/Boop#93]
Running a script on full text (I mean, no selection) that contains Unicode chars with cause an unexpected result:

![屏幕快照 2020-07-02 11.13.18](https://tva1.sinaimg.cn/large/007S8ZIlgy1ggcgh7n0kij31mi0mknmn.jpg)

Emmm, this is exactly not an issue of Base64Encode script. Whit this text, Any script result with a funny [U+DE00](https://www.fileformat.info/info/unicode/char/de00/index.htm) char:

![屏幕快照 2020-07-02 11.18.22](https://tva1.sinaimg.cn/large/007S8ZIlgy1ggcgmjjcj4j31eu0i4h1t.jpg)

If we add more utf-16 chars into the text, it bombs (Some utf-16 chars are static here):

![屏幕快照 2020-07-02 11.22.40](https://tva1.sinaimg.cn/large/007S8ZIlgy1ggcgqhyvtdj31l60iy7lw.jpg)

My version is 1.1.0 (3) from App Store

**Comment by cdfmlr** [comment]
Humm, self help:🤪

I just peeked the code and tried something in a playground. I guess I can say that this issue is caused by `replaceCharacters` with a wrong range.

```swift
import AppKit
import Foundation
import PlaygroundSupport

var textStorage: NSTextStorage = NSTextStorage()

textStorage.replaceCharacters(
    in: NSRange(location: 0, length: textStorage.string.count),
    with: "hello，世界！😀")

textStorage.string.count
textStorage.length

let range = NSRange(location: 0, length: textStorage.string.count)
//let range = NSRange(location: 0, length: textStorage.length)

textStorage.replaceCharacters(in: range, with: "")

let length = textStorage.string.count

```


![image-20200702113610189](https://tva1.sinaimg.cn/large/007S8ZIlgy1ggch3f1zjnj31gn0u0auk.jpg)

As we can see, different from  `string.count`, a utf-16 char in `NSTextStorage` is not length one.

Replace `textStorage.string.count` with a `textStorage.length` helps a lot:

![image-20200702114557081](https://tva1.sinaimg.cn/large/007S8ZIlgy1ggchdl3xlej31gn0u0e0a.jpg)

This is not a big problem, I am now working on this, PR to solve it soon.

**Comment by IvanMathy** [comment]
Oh wow, this explains a lot of issues I've been seeing lately but could not pinpoint... Thank you so much for taking the time to document it, research it, and fix it! It would have taken me a while to realize all those were linked, and even more so to figure out how to address it.

I'll test your changes and merge it all in. Thank you again!

**Comment by IvanMathy** [comment]
Merged, thanks for the help!
