### ISSUE TITLE
Word Counter

### ISSUE THREAD

**Issue by daniel-stoneuk** [IvanMathy/Boop#97]
Hi,

Thanks for the excellent app - such a great idea and has come in handy already. One small thing, though, there's a character counter and a line counter but no word counter! 

If it helps and you would like to merge a word counter, I can work on one. Let me know.

Thanks

**Comment by IvanMathy** [comment]
Good idea! I can add it in, or if you feel like it you can go ahead and submit a PR. Thanks!

**Comment by daniel-stoneuk** [comment]
I'll give it a go and submit a PR. Cheers!

**Comment by IvanMathy** [comment]
Fixed by #104, will be in the next release!
